### ISSUE TITLE
Proposed Wiki edits

### ISSUE THREAD

**Issue by aequi42** [openbrewhub/open-brew#1]
Hi,
a few proposals for the [wiki wording page](https://github.com/SeeSharp7/Open-Brew/wiki/Wording):

German|English|Definition
-------|--------|-------|
Maische|maish (mash)|blabla
Läutern|lautering (purify)|Extract solids from the maish
Gärung|fermenting|Convert sugar to gases, or alcohol
Brauen|brew|Make some tasty beverages|

Inspiration for translations are found [here](http://craftbeertemple.com/videoblog/brewing-process/)

**Comment by SeeSharp7** [comment]
Thank you very much! 👍
