### ISSUE TITLE
Remove 'sequence' from brewStep?

### ISSUE THREAD

**Issue by SeeSharp7** [openbrewhub/open-brew#2]
The order of elements in json arrays is guaranteed, isn't it? So we don't need the `sequence` element for specifing the correct order.

**Comment by aequi42** [comment]
[RFC 7159](http://www.rfc-editor.org/rfc/rfc7159.txt) says arrays are ordered. 
There shouldn't be a problem in omitting the `sequence`-property.

**Comment by SeeSharp7** [comment]
Cool, let's kick it out! :)
