### ISSUE TITLE
Rename the customs Property

### ISSUE THREAD

**Issue by aequi42** [openbrewhub/open-brew#3]
In english "customs" means a athority the collects duties on imported goods :D (German: Zoll)
Maby renaming `customs` to `additional` or something similar wouldn't be to bad.

**Comment by SeeSharp7** [comment]
I really should use dict.cc always ;) Thanks for that hint! :+1:

**Comment by SeeSharp7** [comment]
`customIngredients`?

**Comment by SeeSharp7** [comment]
Naaaaah, after checkin I started hating my idea -.- What about `additionalIngredients`?
