### ISSUE TITLE
CreateDate/ChangeDate necessary?

### ISSUE THREAD

**Issue by SeeSharp7** [openbrewhub/open-brew#4]
A colleague had the idea with Create- and Changedate fields. I think this could be useful. Other opinions?

**Comment by sevensc** [comment]
I think its good to employ both. Another option would be, to use only a changedate. Is it important to keep the create date?

**Comment by SeeSharp7** [comment]
Is it important to implement any of these date fields? Probably not. But it could be very interesting! And so both elements are qualified :) ChangeDate only is a possibility. CreateDate only also. But when we make use of that, we should take both, I think. I will add these fields now. Additional meanings welcome!
